version: '3'

services:
  order-service:
    build:
      context: order-service
      dockerfile: order-service.Dockerfile
    ports:
      - "8081:80"
    depends_on:
      - postgres
    environment:
      POSTGRES_CONNECTION_STRING: "host=postgres port=5432 user=postgres password=password dbname=order_db sslmode=disable"
  scraper-service:
    build:
      context: scraper-service
      dockerfile: scraper-service.Dockerfile
  notifier-service:
    build:
      context: notifier-service
      dockerfile: notifier-service.Dockerfile
    environment:
      TWILIO_FROM_PHONE_NUMBER: ""
      TWILIO_ACCOUNT_SID: ""
      TWILIO_AUTH_TOKEN: ""
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: order_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  mongo:
    image: 'mongo:4.2.17-bionic'
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: notificationsdb
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo_data:/data/db
volumes:
  postgres_data:
  mongo_data:
