version: '3'

services:
  order-service:
    build:
      context: order-service
      dockerfile: order-service.Dockerfile
    ports:
      - "8081:80"
    depends_on:
      - postgres
    environment:
      POSTGRES_CONNECTION_STRING: "host=postgres port=5432 user=postgres password=password dbname=order_db sslmode=disable"
  scraper-service:
    build:
      context: scraper-service
      dockerfile: scraper-service.Dockerfile
    environment:
      RABBITMQ_CONNECTION_STRING: "amqp://guest:guest@rabbitmq:5672"
  mailer-service:
    build:
      context: mailer-service
      dockerfile: mailer-service.Dockerfile
    environment:
      MAIL_DOMAIN: localhost
      MAIL_HOST: mailhog
      MAIL_PORT: 1025
      MAIL_ENCRYPTION: none
      MAIL_USERNAME: ""
      MAIL_PASSWORD: ""
      FROM_NAME: "John Doe"
      FROM_ADDRESS: john.doe@example.com
  listener-service:
    build:
      context: listener-service
      dockerfile: listener-service.Dockerfile
    environment:
      RABBITMQ_CONNECTION_STRING: "amqp://guest:guest@rabbitmq:5672"
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: order_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  rabbitmq:
    image: 'rabbitmq:3-management-alpine'
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
  mailhog:
    image: 'mailhog/mailhog:latest'
    ports:
      - "1025:1025"
      - "8025:8025"
volumes:
  postgres_data:
  rabbitmq_data:
