name: Frontend Successfully Builds

on:
  pull_request:
    branches: [main]

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Install Dependencies
        run: cd frontend && npm ci

      - name: Build
        run: cd frontend && npm run build
